<?php

class DBConfig {
    //All table configuration for user controller
    //define tbl_user

    CONST TABLE_USER = 'tbl_user';
    CONST TABLE_USER_ATT_USER_ID = 'userId';
    CONST TABLE_USER_ATT_NAME = 'name';
    CONST TABLE_USER_ATT_EMAIL = 'email';
    CONST TABLE_USER_ATT_PASSWORD = 'password';
    CONST TABLE_USER_ATT_STATE_ID = 'stateId';
    CONST TABLE_USER_ATT_CITY_ID = 'cityId';
    CONST TABLE_USER_ATT_ZIP_CODE = 'zipcode';
    CONST TABLE_USER_ATT_WHICH_BEST = 'whichBest';
    CONST TABLE_USER_ATT_IP_ADDRESS = 'ipAddress';
    CONST TABLE_USER_ATT_LAST_LOGIN_DATE = 'lastLoginDate';
    CONST TABLE_USER_ATT_REGISTRATION_DATE = 'registrationDate';
    CONST TABLE_USER_ATT_STATUS = 'status';

    //define tbl_state
    CONST TABLE_STATE = 'tbl_state';
    CONST TABLE_STATE_ATT_STATE_ID = 'stateId';
    CONST TABLE_STATE_ATT_STATE_NAME = 'stateName';
    CONST TABLE_STATE_ATT_COUNTRY_ID = 'countryId';

    //define tbl_city
    CONST TABLE_CITY = 'tbl_city';
    CONST TABLE_CITY_ATT_CITY_ID = 'cityId';
    CONST TABLE_CITY_ATT_CITY_NAME = 'cityName';
    CONST TABLE_CITY_ATT_STATE_ID = 'stateId';

    //define tbl_category
    CONST TABLE_CATEGORY = 'tbl_category';
    CONST TABLE_CATEGORY_ATT_CATEGORY_ID = 'categoryId';
    CONST TABLE_CATEGORY_ATT_CATEGORY_NAME = 'categoryName';

    //define tbl_event_type
    CONST TABLE_EVENT_TYPE = 'tbl_event_type';
    CONST TABLE_EVENT_TYPE_ATT_EVENT_ID = 'eventId';
    CONST TABLE_EVENT_TYPE_ATT_EVENT_NAME = 'eventName';
    CONST TABLE_EVENT_TYPE_ATT_STATUS = 'status';

    //define tbl_event
    CONST TABLE_EVENT='tbl_event';
    CONST TABLE_EVENT_ATT_EVENT_ID='eventId';
    CONST TABLE_EVENT_ATT_CATEGORY_ID='categoryId';
    CONST TABLE_EVENT_ATT_EVENT_DATE='eventDate';
    CONST TABLE_EVENT_ATT_CITY_ID='cityId';
    CONST TABLE_EVENT_ATT_EVENT_TYPE_ID='eventTypeId';
    CONST TABLE_EVENT_ATT_NUMBER_OF_GUESTS='numberOfGuests';
    CONST TABLE_EVENT_ATT_EVENT_LOCATION='eventLocation';
    CONST TABLE_EVENT_ATT_NAME='name';
    CONST TABLE_EVENT_ATT_PHONE='phone';
    CONST TABLE_EVENT_ATT_EMAIL='email';
    CONST TABLE_EVENT_ATT_VENUE_BUDGET_ID='venueBudgetId';
    CONST TABLE_EVENT_ATT_START_TIME='startTime';
    CONST TABLE_EVENT_ATT_EVENT_CREATED_DATE='eventCreatedDate';
    CONST TABLE_EVENT_ATT_STATUS='status';
    
    //define tbl_venue_budget
    CONST TABLE_VENUE_BUDGET='tbl_venue_budget';
    CONST TABLE_VENUE_BUDGET_ATT_VENUE_BUDGET_ID='venueBudgetId';
    CONST TABLE_VENUE_BUDGET_ATT_BUDGET_RANGE='budgetRange';
    
    //define tbl_amenities_type
    CONST TABLE_AMENITIES_TYPE='tbl_amenities_type';
    CONST TABLE_AMENITIES_TYPE_ATT_AMENITIES_TYPE_ID='amenitiesTypeId';
    CONST TABLE_AMENITIES_TYPE_ATT_AMENITIES_TYPE='amenitiesType';
    CONST TABLE_AMENITIES_TYPE_ATT_STATUS='status';
    
    //define tbl_additional_service
    CONST TABLE_ADDITIONAL_SERVICE='tbl_additional_service';
    CONST TABLE_ADDITIONAL_SERVICE_ATT_ADDITIONAL_SERVICE_ID='additionalServiceId';
    CONST TABLE_ADDITIONAL_SERVICE_ATT_ADDITIONAL_SERVICE='additionalService';
    CONST TABLE_ADDITIONAL_SERVICE_ATT_STATUS='status';
    
    //define tbl_budget_per_person
    CONST TABLE_BUDGET_PER_PERSON='tbl_budget_per_person';
    CONST TABLE_BUDGET_PER_PERSON_ATT_BUDGET_PER_PERSON_ID='budgetPerPersonId';
    CONST TABLE_BUDGET_PER_PERSON_ATT_BUDGET_PER_PERSON='budgetPerPerson';
    CONST TABLE_BUDGET_PER_PERSON_ATT_STATUS='status';
    
    //define  tbl_flowers_type
    CONST TABLE_FLOWERS_TYPE='tbl_flowers_type';
    CONST TABLE_FLOWERS_TYPE_ATT_FLOWERS_TYPE_ID='flowersTypeId';
    CONST TABLE_FLOWERS_TYPE_ATT_FLOWERS_TYPE='flowersType';
    CONST TABLE_FLOWERS_TYPE_ATT_STATUS='status';
    
    //define tbl_food_type
    CONST TABLE_FOOD_TYPE='tbl_food_type';
    CONST TABLE_FOOD_TYPE_ATT_FOOD_TYPE_ID='foodTypeId';
    CONST TABLE_FOOD_TYPE_ATT_FOOD_TYPE='foodType';
    CONST TABLE_FOOD_TYPE_ATT_STATUS='status';
    
    //define tbl_music_type
    CONST TABLE_MUSIC_TYPE='tbl_music_type';
    CONST TABLE_MUSIC_TYPE_ATT_MUSIC_TYPE_ID='musicTypeId';
    CONST TABLE_MUSIC_TYPE_ATT_MUSIC_TYPE='musicType';
    CONST TABLE_MUSIC_TYPE_ATT_STATUS='status';
    
    //define tbl_service
    CONST TABLE_SERVICE='tbl_service';
    CONST TABLE_SERVICE_ATT_SERVICE_ID='serviceId';
    CONST TABLE_SERVICE_ATT_SERVICE='service';
    CONST TABLE_SERVICE_ATT_STATUS='status';
    
    //define tbl_transportation_type
    CONST TABLE_TRANSPORTATION_TYPE='tbl_transportation_type';
    CONST TABLE_TRANSPORTATION_TYPE_ATT_TRANSPORTATION_TYPE_ID='transportationTypeId';
    CONST TABLE_TRANSPORTATION_TYPE_ATT_TRANSPORTATION_TYPE='transportationType';
    CONST TABLE_TRANSPORTATION_TYPE_ATT_STATUS='status';
    
    //define tbl_venue_type
    CONST TABLE_VENUE_TYPE='tbl_venue_type';
    CONST TABLE_VENUE_TYPE_ATT_VENUE_TYPE_ID='venueTypeId';
    CONST TABLE_VENUE_TYPE_ATT_VENUE_TYPE='venueType';
    CONST TABLE_VENUE_TYPE_ATT_STATUS='status';
    
    //define tbl_service_budget
    CONST TABLE_SERVICE_BUDGET='tbl_service_budget';
    CONST TABLE_SERVICE_BUDGET_ATT_SERVICE_BUDGET_ID='serviceBudgetId';
    CONST TABLE_SERVICE_BUDGET_ATT_SERVICE_BUDGET='serviceBudget';
    
    //define tbl_photography_style
    CONST TABLE_PHOTOGRAPHY_STYLE='tbl_photography_style';
    CONST TABLE_PHOTOGRAPHY_STYLE_ATT_STYLE_ID='styleId';
    CONST TABLE_PHOTOGRAPHY_STYLE_ATT_STYLE='style';
    CONST TABLE_PHOTOGRAPHY_STYLE_ATT_STATUS='status';
    
    //define tbl_food_preference
    CONST TABLE_FOOD_PREFERENCE='tbl_food_preference';
    CONST TABLE_FOOD_PREFERENCE_ATT_FOOD_PREFERENCE_ID='foodPreferenceId';
    CONST TABLE_FOOD_PREFERENCE_ATT_EVENT_ID='eventId';
    CONST TABLE_FOOD_PREFERENCE_ATT_SERVICE_ID='serviceId';
    CONST TABLE_FOOD_PREFERENCE_ATT_BUDGET_PET_PERSON_ID='budgetPerPersonId';
    CONST TABLE_FOOD_PREFERENCE_ATT_FOOD_TYPE='foodType';
    CONST TABLE_FOOD_PREFERENCE_ATT_VENUE_NAME='venueName';
    CONST TABLE_FOOD_PREFERENCE_ATT_KITCHEN='kitchen';
    CONST TABLE_FOOD_PREFERENCE_ATT_ABOUT_EVENT='aboutEvent';
    
    //define tbl_halls_quotes
    CONST TABLE_HALLS_QUOTES='tbl_halls_quotes';
    CONST TABLE_HALLS_QUOTES_ATT_HALLS_QUOTES_ID='hallsQuotesId';
    CONST TABLE_HALLS_QUOTES_ATT_EVENT_ID='eventId';
    CONST TABLE_HALLS_QUOTES_ATT_HALLS_TYPE='hallType';
    CONST TABLE_HALLS_QUOTES_ATT_START_TIME='startTime';
    CONST TABLE_HALLS_QUOTES_ATT_END_TIME='endTime';
    CONST TABLE_HALLS_QUOTES_ATT_NEED_CATERING='needCatering';
    CONST TABLE_HALLS_QUOTES_ATT_VENUE_CHOICE='venueChoice';
    CONST TABLE_HALLS_QUOTES_ATT_AMENITIES_TYPES='amenitiesTypes';
    CONST TABLE_HALLS_QUOTES_ATT_EVENT_COMMENTS='eventComments';
    
    //define tbl_dj_quotes
    CONST TABLE_DJ_QUOTES='tbl_dj_quotes';
    CONST TABLE_DJ_QUOTES_ATT_DJ_QUOTES_ID='djQuotesId';
    CONST TABLE_DJ_QUOTES_ATT_EVENT_ID='eventId';
    CONST TABLE_DJ_QUOTES_ATT_MUSIC_TYPES='musicTypes';
    CONST TABLE_DJ_QUOTES_ATT_SERVICE_BUDGET_ID='serviceBudgetId';
    CONST TABLE_DJ_QUOTES_ATT_DJ_TYPE='djType';
    CONST TABLE_DJ_QUOTES_ATT_EVENT_COMMENTS='eventComments';
    
    CONST TABLE_ADMIN = 'tbl_admin';
    CONST TABLE_ADMIN_ATT_ADMIN_ID = 'adminId';
    CONST TABLE_ADMIN_ATT_ADMIN_USERNAME = 'adminUsername';
    CONST TABLE_ADMIN_ATT_ADMIN_PASSWORD = 'adminPassword';
    CONST TABLE_ADMIN_ATT_ADMIN_LAST_LOGIN_TIME = 'adminLastLoginTime';
    CONST TABLE_ADMIN_ATT_ADMIN_IS_ACTIVE = 'adminIsActive';
    CONST TABLE_ADMIN_ATT_ADMIN_PREVILEDGE = 'adminPreviledge';
    
    CONST TABLE_CONTENT = 'tbl_content';
    CONST TABLE_CONTENT_ATT_CONTENT_ID = 'contentId';
    CONST TABLE_CONTENT_ATT_CONTENT_NAME = 'contentName';
    CONST TABLE_CONTENT_ATT_CONTENT_TITLE = 'contentTitle';
    CONST TABLE_CONTENT_ATT_CONTENT_DETAILS = 'contentDetails';
    
    CONST TABLE_FAQ = 'tbl_faq';
    CONST TABLE_FAQ_ATT_FAQ_ID = 'faqId';
    CONST TABLE_FAQ_ATT_FAQ_QUESTION = 'faqQuestion';
    CONST TABLE_FAQ_ATT_FAQ_ANSWER = 'faqAnswer';
    CONST TABLE_FAQ_ATT_ADDED_TIME = 'addedTime';
    
    CONST TABLE_SERVICE_LIST = 'tbl_service_list';
    CONST TABLE_SERVICE_LIST_ATT_SERVICE_LIST_ID = 'serviceListId';
    CONST TABLE_SERVICE_LIST_ATT_SERVICE_LIST_NAME = 'serviceListName';
    
    CONST TABLE_AGE_RANGE = 'tbl_age_range';
    CONST TABLE_AGE_RANGE_ATT_AGE_RANGE_ID = 'ageRangeId';
    CONST TABLE_AGE_RANGE_ATT_AGE_RANGE = 'ageRange';
    CONST TABLE_AGE_RANGE_ATT_IS_ACTIVE = 'isActive';
    
    CONST TABLE_ENTERTAINMENT_TYPE = 'tbl_entertainment_type';
    CONST TABLE_ENTERTAINMENT_TYPE_ATT_ENTERTAINMENT_TYPE_ID = 'entertainmentTypeId';
    CONST TABLE_ENTERTAINMENT_TYPE_ATT_ENTERTAINMENT_TYPE = 'entertainmentType';
    CONST TABLE_ENTERTAINMENT_TYPE_ATT_IS_ACTIVE = 'isActive';
    
    CONST TABLE_ENTERTAINMENT_BUDGET = 'tbl_entertainment_budget';
    CONST TABLE_ENTERTAINMENT_BUDGET_ATT_BUDGET_ID = 'budgetId';
    CONST TABLE_ENTERTAINMENT_BUDGET_ATT_BUDGET_RANGE = 'budgetRange';
    
    CONST TABLE_VENDOR = 'tbl_vendor';
    CONST TABLE_VENDOR_ATT_VENDOR_ID = 'vendorId';
    CONST TABLE_VENDOR_ATT_VENDOR_BUSINESS_NAME = 'vendorBusinessName';
    CONST TABLE_VENDOR_ATT_VENDOR_PROFILE_IMAGE = 'vendorProfileImage';
    CONST TABLE_VENDOR_ATT_VENDOR_NAME = 'vendorName';
    CONST TABLE_VENDOR_ATT_VENDOR_PHONE = 'vendorPhone';
    CONST TABLE_VENDOR_ATT_VENDOR_EMAIL = 'vendorEmail';
    CONST TABLE_VENDOR_ATT_VENDOR_PASSWORD = 'vendorPassword';
    CONST TABLE_VENDOR_ATT_VENDOR_ADDRESS = 'vendorAddress';
    CONST TABLE_VENDOR_ATT_VENDOR_STATE_ID = 'vendorStateId';
    CONST TABLE_VENDOR_ATT_VENDOR_CITY_ID = 'vendorCityId';
    CONST TABLE_VENDOR_ATT_VENDOR_ZIP = 'vendorZip';
    CONST TABLE_VENDOR_ATT_VENDOR_WEB_URL = 'vendorWebUrl';
    CONST TABLE_VENDOR_ATT_VENDOR_SERVICES = 'vendorServices';
    CONST TABLE_VENDOR_ATT_VENDOR_STATUS = 'vendorStatus';
    CONST TABLE_VENDOR_ATT_VENDOR_REGISTRATION_DATE = 'vendorRegistrationDate';
    CONST TABLE_VENDOR_ATT_VENDOR_LAST_LOGIN = 'vendorLastLogin';
    CONST TABLE_VENDOR_ATT_VENDOR_REGISTRATION_TOKEN = 'vendorRegistrationToken';
    
    CONST TABLE_EQUIPMENT = 'tbl_equipment';
    CONST TABLE_EQUIPMENT_ATT_EQUIPMENT_ID = 'equipmentId';
    CONST TABLE_EQUIPMENT_ATT_EQUIPMENT_NAME = 'equipmentName';
    
    CONST TABLE_ARRANGMENT_TYPE = 'tbl_arrangement_type';
    CONST TABLE_ARRANGMENT_TYPE_ATT_ARRANGMENT_TYPE_ID = 'arrangementTypeId';
    CONST TABLE_ARRANGMENT_TYPE_ATT_ARRANGMENT_TYPE = 'arrangementType';
    
    CONST TABLE_SETTINGS = 'tbl_settings';
    CONST TABLE_SETTINGS_ATT_ID = 'id';
    CONST TABLE_SETTINGS_ATT_SITE_TITLE = 'siteTitle';
    CONST TABLE_SETTINGS_ATT_SITE_META_KEYWORD = 'siteMetaKeyword';
    CONST TABLE_SETTINGS_ATT_SITE_META_DESCRIPTION = 'siteMetaDescription';
    CONST TABLE_SETTINGS_ATT_SITE_LOGO = 'siteLogo';
    CONST TABLE_SETTINGS_ATT_SITE_EMAIL = 'siteEmail';
    CONST TABLE_SETTINGS_ATT_SITE_PHONE = 'sitePhone';
    CONST TABLE_SETTINGS_ATT_SITE_VENDOR_LOGO = 'siteVendorLogo';
    CONST TABLE_SETTINGS_ATT_HIDE_HOME_CONTENT = 'hideHomeContent';
    
    CONST TABLE_SUBSCRIBER = 'tbl_subscriber';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_ID = 'subscriberId';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_NAME = 'subscriberName';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_EMAIL = 'subscriberEmail';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_ZIP_CODE = 'subscriberZipcode';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_DETAILS = 'subscriberDetails';
    CONST TABLE_SUBSCRIBER_ATT_SUBSCRIBER_DATE_TIME = 'subscriberDatetime';
    
    CONST TABLE_DRINKS_TYPE='tbl_drinks_type';
    CONST TABLE_DRINKS_TYPE_ATT_DRINKS_TYPE_ID='drinksTypeId';
    CONST TABLE_DRINKS_TYPE_ATT_DRINKS_TYPE='drinksType';

    CONST TABLE_EVENT_INFO='tbl_event_info';
    CONST TABLE_EVENT_INFO_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_EVENT_INFO_ATT_EVENT_TYPE_ID='eventTypeId';
    CONST TABLE_EVENT_INFO_ATT_OTHER_EVENT_TYPE='otherEventType';
    CONST TABLE_EVENT_INFO_ATT_EVENT_CATEGORY='eventCategory';
    CONST TABLE_EVENT_INFO_ATT_EVENT_NAME='eventName';
    CONST TABLE_EVENT_INFO_ATT_STATE_ID='stateId';
    CONST TABLE_EVENT_INFO_ATT_CITY_ID='cityId';
    CONST TABLE_EVENT_INFO_ATT_USER_ID='userId';
    CONST TABLE_EVENT_INFO_ATT_ADDED_DATE='addedDate';

    CONST TABLE_CATERING='tbl_catering';
    CONST TABLE_CATERING_ATT_CATERING_ID='cateringId';
    CONST TABLE_CATERING_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_CATERING_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_CATERING_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_CATERING_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_CATERING_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_CATERING_ATT_DATES_FLEXIBLE='datesFlexible';
    CONST TABLE_CATERING_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_CATERING_ATT_SERVICE_ID='serviceId';
    CONST TABLE_CATERING_ATT_FOOD_TYPE_ID='foodTypeId';
    CONST TABLE_CATERING_ATT_OTHERS_FOOD_TYPE='othersFoodType';
    CONST TABLE_CATERING_ATT_COURSES='courses';
    CONST TABLE_CATERING_ATT_EQUIPMENT='equipment';
    CONST TABLE_CATERING_ATT_OTHER_EQUIPMENT='otherEquipment';
    CONST TABLE_CATERING_ATT_ADDITIONAL_SERVICES='additionalServices';
    CONST TABLE_CATERING_ATT_OTHER_ADDITIONAL_SERVICES='otherAdditionalServices';
    CONST TABLE_CATERING_ATT_SET_EVENT_LOCATION='setEventLocation';
    CONST TABLE_CATERING_ATT_VENUE_TYPE_ID='venueTypeId';
    CONST TABLE_CATERING_ATT_KITCHEN_AVAILABLITY='kitchenAvailablity';
    CONST TABLE_CATERING_ATT_BUDGET_PER_PERSON_ID='budgetPerPersonId';
    CONST TABLE_CATERING_ATT_ADDITIONAL_COMMENTS='additionalComments';

    CONST TABLE_RECEPTION_HALLS='tbl_reception_halls';
    CONST TABLE_RECEPTION_HALLS_ATT_RECEPTION_ID='receptionId';
    CONST TABLE_RECEPTION_HALLS_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_RECEPTION_HALLS_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_RECEPTION_HALLS_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_RECEPTION_HALLS_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_RECEPTION_HALLS_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_RECEPTION_HALLS_ATT_DATE_FLEXIBLE='datesFlexible';
    CONST TABLE_RECEPTION_HALLS_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_RECEPTION_HALLS_ATT_SERVICE_ID='serviceId';
    CONST TABLE_RECEPTION_HALLS_ATT_AMENITIES_TYPE='amenitiesType';
    CONST TABLE_RECEPTION_HALLS_ATT_ADDITIONAL_COMMENTS='additionalComments';
    
    CONST TABLE_ENTERTAINMENT='tbl_entertainment';
    CONST TABLE_ENTERTAINMENT_ATT_ENTERTAINMENT_ID='entertainmentId';
    CONST TABLE_ENTERTAINMENT_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_ENTERTAINMENT_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_ENTERTAINMENT_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_ENTERTAINMENT_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_ENTERTAINMENT_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_ENTERTAINMENT_ATT_DATE_FLEXIBLE='datesFlexible';
    CONST TABLE_ENTERTAINMENT_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_ENTERTAINMENT_ATT_AGE_RANGE_ID='ageRangeId';
    CONST TABLE_ENTERTAINMENT_ATT_EVENT_SETTING='eventSetting';
    CONST TABLE_ENTERTAINMENT_ATT_SETTING_ADDITIONAL='settingAdditional';
    CONST TABLE_ENTERTAINMENT_ATT_ENTERTAINMENT_TYPE='entertainmentType';
    CONST TABLE_ENTERTAINMENT_ATT_OTHER_ENTERTAINMENT='otherEntertainment';
    CONST TABLE_ENTERTAINMENT_ATT_ENTERTAINMENT_BUDGET_ID='entertainmentBudgetId';
    CONST TABLE_ENTERTAINMENT_ATT_ADDITIONAL_COMMENTS='additionalComments';
    
    CONST TABLE_FLORISTS='tbl_florists';
    CONST TABLE_FLORISTS_ATT_FLORISTS_ID='floristsId';
    CONST TABLE_FLORISTS_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_FLORISTS_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_FLORISTS_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_FLORISTS_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_FLORISTS_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_FLORISTS_ATT_DATE_FLEXIBLE='datesFlexible';
    CONST TABLE_FLORISTS_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_FLORISTS_ATT_FLORISTS_SERVICE='floristsService';
    CONST TABLE_FLORISTS_ATT_FLOWER_TYPE='flowerType';
    CONST TABLE_FLORISTS_ATT_ARRANGEMENT_TYPE='arrangementType';
    CONST TABLE_FLORISTS_ATT_FLOWERS_DETAILS='flowersDetails';
    CONST TABLE_FLORISTS_ATT_FLORIST_BUDGET_ID='floristBudgetId';
    CONST TABLE_FLORISTS_ATT_ADDITIONAL_COMMENT='additionalComment';
    
    CONST TABLE_PHOTOGRAPHY='tbl_photography';
    CONST TABLE_PHOTOGRAPHY_ATT_PHOTOGRAPHY_ID='photographyId';
    CONST TABLE_PHOTOGRAPHY_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_PHOTOGRAPHY_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_PHOTOGRAPHY_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_PHOTOGRAPHY_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_PHOTOGRAPHY_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_PHOTOGRAPHY_ATT_DATE_FLEXIBLE='datesFlexible';
    CONST TABLE_PHOTOGRAPHY_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_PHOTOGRAPHY_ATT_PHOTOGRAPHY_STYLE_ID='photographyStyleId';
    CONST TABLE_PHOTOGRAPHY_ATT_SETTING_TYPE='settingType';
    CONST TABLE_PHOTOGRAPHY_ATT_SETTING_LOCATION='settingLocation';
    CONST TABLE_PHOTOGRAPHY_ATT_REQUIRMENTS='requirements';
    CONST TABLE_PHOTOGRAPHY_ATT_PHOTOGRAPHY_BUDGET_ID='photographyBudgetId';
    CONST TABLE_PHOTOGRAPHY_ATT_ADDITIONAL_COMMENT='additionalComment';
    
    CONST TABLE_LIQUOR='tbl_liquor';
    CONST TABLE_LIQUOR_ATT_LIQUOR_ID='liquorId';
    CONST TABLE_LIQUOR_ATT_EVENT_INFO_ID='eventInfoId';
    CONST TABLE_LIQUOR_ATT_EVENT_START_DATE='eventStartDate';
    CONST TABLE_LIQUOR_ATT_APPROX_START_TIME='approxStartTime';
    CONST TABLE_LIQUOR_ATT_EVENT_END_DATE='eventEndDate';
    CONST TABLE_LIQUOR_ATT_APPROX_END_TIME='approxEndTime';
    CONST TABLE_LIQUOR_ATT_DATE_FLEXIBLE='datesFlexible';
    CONST TABLE_LIQUOR_ATT_GUESTS_NUMBER='guestsNumber';
    CONST TABLE_LIQUOR_ATT_SERVICE_ID='serviceId';
    CONST TABLE_LIQUOR_ATT_DRINK_TYPES='drinkTypes';
    CONST TABLE_LIQUOR_ATT_RENT_GLASSES='rentGlasses';
    CONST TABLE_LIQUOR_ATT_GLASSES_QUANTITY='glassesQuantity';
    CONST TABLE_LIQUOR_ATT_ADDITIONAL_COMMENT='additionalComments';
    
    CONST TABLE_BOOKMARK = 'tbl_bookmark';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_ID = 'bookmarkId';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_SERVICE_ID = 'bookmarkServiceId';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_EVENTS_INFO_ID = 'bookmarkEventsInfoId';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_SERVICE_LIST_ID = 'bookmarkServiceListId';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_DATE = 'bookmarkDate';
    CONST TABLE_BOOKMARK_ATT_BOOKMARK_VENDOR_ID = 'bookmarkVendorId';
    
    CONST TABLE_VENDOR_REVIEW='tbl_vendor_review';
    CONST TABLE_VENDOR_REVIEW_ATT_REVIEW_ID='reviewId';
    CONST TABLE_VENDOR_REVIEW_ATT_VENDOR_ID='vendorId';
    CONST TABLE_VENDOR_REVIEW_ATT_USER_ID='userId';
    CONST TABLE_VENDOR_REVIEW_ATT_REVIEW='review';
    CONST TABLE_VENDOR_REVIEW_ATT_REVIEW_DATE='reviewDate';
    CONST TABLE_VENDOR_REVIEW_ATT_IS_ACTIVE='isActive';
    
    CONST TABLE_FAVORITE='tbl_favorite';
    CONST TABLE_FAVORITE_ATT_FAVORITE_ID='favoriteId';
    CONST TABLE_FAVORITE_ATT_VENDOR_ID='vendorId';
    CONST TABLE_FAVORITE_ATT_USER_ID='userId';
    CONST TABLE_FAVORITE_ATT_FAVORITE_DATE='favoriteDate';
    
    CONST TABLE_EVENT_MESSAGE = 'tbl_event_message';
    CONST TABLE_EVENT_MESSAGE_ATT_MESSAGE_ID = 'messageId';
    CONST TABLE_EVENT_MESSAGE_ATT_EVENT_INFO_ID = 'eventInfoId';
    CONST TABLE_EVENT_MESSAGE_ATT_SENDER_ID = 'messageSenderId';
    CONST TABLE_EVENT_MESSAGE_ATT_SENDER_TYPE = 'messageSenderType';
    CONST TABLE_EVENT_MESSAGE_ATT_RECEIVER_ID = 'messageReceiverId';
    CONST TABLE_EVENT_MESSAGE_ATT_MESSAGE_TITLE = 'messageTitle';
    CONST TABLE_EVENT_MESSAGE_ATT_MESSAGE_DETAILS = 'messageDescription';
    CONST TABLE_EVENT_MESSAGE_ATT_MESSAGE_SENDING_DATE = 'messageSendingDate';
    CONST TABLE_EVENT_MESSAGE_ATT_MESSAGE_IS_READ = 'messageIsRead';
    
    CONST TABLE_VENDOR_RATING='tbl_vendor_rating';
    CONST TABLE_VENDOR_RATING_ATT_RATING_ID='ratingId';
    CONST TABLE_VENDOR_RATING_ATT_USER_ID='userId';
    CONST TABLE_VENDOR_RATING_ATT_VENDOR_ID='vendorId';
    CONST TABLE_VENDOR_RATING_ATT_RATING='rating';
    CONST TABLE_VENDOR_RATING_ATT_RATED_DATE='ratedDate';
    
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION = 'tbl_event_message_report_violation';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_ID = 'reportViolationId';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_EVENT_INFO_ID = 'reportViolationEventInfoId';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_REPORTER_ID = 'reportViolationReporterId';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_VIOLATED_BY_ID = 'reportViolatedById';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_REPORTER_TYPE = 'reportViolationReporterType';
    CONST TABLE_EVENT_MESSAGE_REPORT_VIOLATION_ATT_REPORT_VIOLATION_REPORTING_TIME = 'reportViolationReportingTime';
    
    CONST TABLE_EMAIL_TEMPLATE = 'tbl_email_template';
    CONST TABLE_EMAIL_TEMPLATE_ATT_EMAIL_TEMPLATE_ID = 'emailTemplateId';
    CONST TABLE_EMAIL_TEMPLATE_ATT_EMAIL_TEMPLATE_TITLE = 'emailTemplateTitle';
    CONST TABLE_EMAIL_TEMPLATE_ATT_EMAIL_TEMPLATE_DETAILS = 'emailTemplateDetails';
    CONST TABLE_EMAIL_TEMPLATE_ATT_EMAIL_TEMPLATE_FOOTER_TXT = 'emailTemplateFooterTxt';
    
    CONST TABLE_VENDOR_REPORT_RATING = 'tbl_vendor_rating_report';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_REPORT_ID = 'reportId';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_RATING_ID = 'ratingId';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_VENDOR_ID = 'vendorId';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_REPORT_REASON = 'reportReason';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_REPORT_TIME = 'time';
    CONST TABLE_VENDOR_REPORT_RATING_ATT_REPORT_STATUS = 'reportStatus';
}
